export const LIST_ALL='LIST_ALL'
export const ADD_TASK ='ADD_TASK'
export const TOGGLE_FROM='TOGGLE_FROM'
export const CLOSE_FORM='CLOSE_FROM'
export const OPEN_FORM='OPEN_FROM'
export const UPDATE_STATUS='UPDATE_STATUS'